# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo.proto',
  package='template',
  syntax='proto3',
  serialized_options=b'Z%arhat.dev/template-proto/templategopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tfoo.proto\x12\x08template\"&\n\x03\x46oo\x12\x0b\n\x01\x61\x18\x01 \x01(\tH\x00\x12\x0b\n\x01\x62\x18\x02 \x01(\x05H\x00\x42\x05\n\x03\x62\x61rB\'Z%arhat.dev/template-proto/templategopbb\x06proto3'
)




_FOO = _descriptor.Descriptor(
  name='Foo',
  full_name='template.Foo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='template.Foo.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='template.Foo.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='bar', full_name='template.Foo.bar',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=23,
  serialized_end=61,
)

_FOO.oneofs_by_name['bar'].fields.append(
  _FOO.fields_by_name['a'])
_FOO.fields_by_name['a'].containing_oneof = _FOO.oneofs_by_name['bar']
_FOO.oneofs_by_name['bar'].fields.append(
  _FOO.fields_by_name['b'])
_FOO.fields_by_name['b'].containing_oneof = _FOO.oneofs_by_name['bar']
DESCRIPTOR.message_types_by_name['Foo'] = _FOO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Foo = _reflection.GeneratedProtocolMessageType('Foo', (_message.Message,), {
  'DESCRIPTOR' : _FOO,
  '__module__' : 'foo_pb2'
  # @@protoc_insertion_point(class_scope:template.Foo)
  })
_sym_db.RegisterMessage(Foo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
