name: CI

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        architecture: x64

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      with:
        version: "2020.8.13" # yamllint disable-line rule:quoted-strings

    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install go1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: "3.13.0" # yamllint disable-line rule:quoted-strings

    - name: Ensure tidy gomod
      run: |
        go mod download -x
        go mod tidy
        if ! git diff --exit-code
        then
          echo "go mod not tidy"
          exit 1
        fi

    - name: Ensure generated protos updated
      run: |
        make install.proto.all
        make gen.proto.all
        if ! git diff --exit-code; then
          echo "proto not updated"
          exit 1
        fi

    # lint requires python environment so do it after `make install.proto.all`
    - name: Lint
      run: |
        make lint.all

    # test requires python environment so do it after `make install.proto.all`
    - name: Test
      run: |
        make test.all

    - name: Report Test Coverage
      uses: codecov/codecov-action@v1
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #   fail_ci_if_error: true # optional (default = false)
